name = "skill-issue"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "skill-issue-db"
database_id = "a050cc0b-0939-4071-969d-a7638e566b80"

[assets]
directory = "./public"
